In [1]:
import pandas as pd
import numpy as np

Load & Explore the Dataset

In [2]:
# Load dataset
df = pd.read_csv("/content/Financial Statements.csv")
df

,Year,Company,Category,Market Cap(in B USD),Revenue,Gross Profit,Net Income,Earning Per Share,EBITDA,Share Holder Equity,...,Current Ratio,Debt/Equity Ratio,ROE,ROA,ROI,Net Profit Margin,Free Cash Flow per Share,Return on Tangible Equity,Number of Employees,Inflation Rate(in US)
0,2022,AAPL,IT,2066.94,394328.0,170782.0,99803.0,6.1100,130541.0,50672.0,...,0.8794,2.3695,196.9589,28.2924,66.6994,25.3096,1.3146,196.9589,164000,8.0028
1,2021,AAPL,IT,2913.28,365817.0,152836.0,94680.0,5.6100,120233.0,63090.0,...,1.0746,1.9768,150.0713,26.9742,54.9839,25.8818,1.3261,150.0713,154000,4.6979
2,2020,AAPL,IT,2255.97,274515.0,104956.0,57411.0,3.2800,77344.0,65339.0,...,1.3636,1.7208,87.8664,17.7256,35.0054,20.9136,1.0183,87.8664,147000,1.2336
3,2019,AAPL,IT,1304.76,260174.0,98392.0,55256.0,2.9700,76477.0,90488.0,...,1.5401,1.1940,61.0645,16.3230,30.3113,21.2381,-0.0388,61.0645,137000,1.8122
4,2018,AAPL,IT,748.54,265595.0,101839.0,59531.0,2.9800,81801.0,107147.0,...,1.1329,1.0685,55.5601,16.2775,29.6348,22.4142,0.7414,55.5601,132000,2.4426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,2013,AMZN,LOGI,182.54,74452.0,20271.0,274.0,0.0295,3998.0,9746.0,...,1.0716,0.3274,2.8114,0.6823,2.1180,0.3680,0.1748,3.8641,117300,1.4648
157,2012,AMZN,LOGI,113.63,61093.0,15122.0,-39.0,-0.0045,2835.0,8192.0,...,1.1207,0.3765,-0.4761,-0.1198,-0.3459,-0.0638,-0.1833,-0.6915,88400,2.0693
158,2011,AMZN,LOGI,78.72,48077.0,10789.0,631.0,0.0685,1945.0,7757.0,...,1.1741,0.0329,8.1346,2.4962,7.8757,1.3125,-0.0490,10.8756,56200,3.1568
159,2010,AMZN,LOGI,80.79,34204.0,7643.0,1152.0,0.1265,1974.0,6864.0,...,1.3254,0.2274,16.7832,6.1286,13.6736,3.3680,-0.0544,20.8885,33700,1.6400
160,2009,AMZN,LOGI,58.24,24509.0,5531.0,902.0,0.1020,1507.0,5257.0,...,1.3304,0.2007,17.1581,6.5301,17.1581,3.6803,0.3303,22.4211,24300,-0.3555

In [ ]:
# Display first few rows
df.head()

,Year,Company,Category,Market Cap(in B USD),Revenue,Gross Profit,Net Income,Earning Per Share,EBITDA,Share Holder Equity,...,Current Ratio,Debt/Equity Ratio,ROE,ROA,ROI,Net Profit Margin,Free Cash Flow per Share,Return on Tangible Equity,Number of Employees,Inflation Rate(in US)
0,2022,AAPL,IT,2066.94,394328.0,170782.0,99803.0,6.11,130541.0,50672.0,...,0.8794,2.3695,196.9589,28.2924,66.6994,25.3096,1.3146,196.9589,164000,8.0028
1,2021,AAPL,IT,2913.28,365817.0,152836.0,94680.0,5.61,120233.0,63090.0,...,1.0746,1.9768,150.0713,26.9742,54.9839,25.8818,1.3261,150.0713,154000,4.6979
2,2020,AAPL,IT,2255.97,274515.0,104956.0,57411.0,3.28,77344.0,65339.0,...,1.3636,1.7208,87.8664,17.7256,35.0054,20.9136,1.0183,87.8664,147000,1.2336
3,2019,AAPL,IT,1304.76,260174.0,98392.0,55256.0,2.97,76477.0,90488.0,...,1.5401,1.1940,61.0645,16.3230,30.3113,21.2381,-0.0388,61.0645,137000,1.8122
4,2018,AAPL,IT,748.54,265595.0,101839.0,59531.0,2.98,81801.0,107147.0,...,1.1329,1.0685,55.5601,16.2775,29.6348,22.4142,0.7414,55.5601,132000,2.4426

In [ ]:
# Check column names
df.columns

Index(['Year', 'Company ', 'Category', 'Market Cap(in B USD)', 'Revenue',
       'Gross Profit', 'Net Income', 'Earning Per Share', 'EBITDA',
       'Share Holder Equity', 'Cash Flow from Operating',
       'Cash Flow from Investing', 'Cash Flow from Financial Activities',
       'Current Ratio', 'Debt/Equity Ratio', 'ROE', 'ROA', 'ROI',
       'Net Profit Margin', 'Free Cash Flow per Share',
       'Return on Tangible Equity', 'Number of Employees',
       'Inflation Rate(in US)'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Year                                 161 non-null    int64
 1   Company                              161 non-null    object
 2   Category                             161 non-null    object
 3   Market Cap(in B USD)                 160 non-null    float64
 4   Revenue                              161 non-null    float64
 5   Gross Profit                         161 non-null    float64
 6   Net Income                           161 non-null    float64
 7   Earning Per Share                    161 non-null    float64
 8   EBITDA                               161 non-null    float64
 9   Share Holder Equity                  161 non-null    float64
 10  Cash Flow from Operating             161 non-null    float64
 11  Cash Flow from Investing             161 non-null    float64
 12  Cash Flow from Financial Activities  161 non-null    float64
 13  Current Ratio                        161 non-null    float64
 14  Debt/Equity Ratio                    161 non-null    float64
 15  ROE                                  161 non-null    float64
 16  ROA                                  161 non-null    float64
 17  ROI                                  161 non-null    float64
 18  Net Profit Margin                    161 non-null    float64
 19  Free Cash Flow per Share             161 non-null    float64
 20  Return on Tangible Equity            161 non-null    float64
 21  Number of Employees                  161 non-null    int64
 22  Inflation Rate(in US)                161 non-null    float64
dtypes: float64(19), int64(2), object(2)
memory usage: 29.1+ KB

In [ ]:
df.describe()

,Year,Market Cap(in B USD),Revenue,Gross Profit,Net Income,Earning Per Share,EBITDA,Share Holder Equity,Cash Flow from Operating,Cash Flow from Investing,...,Current Ratio,Debt/Equity Ratio,ROE,ROA,ROI,Net Profit Margin,Free Cash Flow per Share,Return on Tangible Equity,Number of Employees,Inflation Rate(in US)
count,161.000000,160.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,...,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,1.610000e+02,161.000000
mean,2015.608696,337.604312,75862.600758,37383.463124,12276.607076,0.982886,20174.023974,57178.005273,20790.317839,-9581.533232,...,2.035368,0.645520,12.432402,7.780479,11.881350,13.684964,0.192825,24.247542,1.457188e+05,2.231317
std,4.049960,541.102812,90786.895983,41669.093697,19417.421119,8.874504,26342.029803,54098.208311,27300.212516,16196.808177,...,1.660894,2.507177,44.777292,8.802462,93.384692,13.401767,15.412788,109.982817,2.234389e+05,1.959139
min,2009.000000,0.040000,3326.445000,1174.269000,-12244.000000,-90.480000,-6860.000000,-8210.300000,-39392.270000,-59611.000000,...,0.220500,-11.775000,-212.606900,-23.723600,-742.105200,-44.696100,-121.502200,-554.174100,5.420000e+03,-0.355500
25%,2012.000000,41.155000,22820.400000,10396.000000,844.000000,0.340000,2310.000000,12353.000000,3502.000000,-17434.000000,...,1.000000,0.077200,5.080000,0.828200,2.757900,4.827700,-0.361300,6.111800,2.990000e+04,1.261600
50%,2016.000000,113.140000,45992.040000,19561.000000,4757.800000,1.790000,9958.000000,47791.000000,7386.700000,-5904.000000,...,1.341200,0.381800,14.501600,6.641100,13.469400,15.297700,0.265600,19.782200,9.600000e+04,1.812200
75%,2019.000000,357.107500,77849.000000,47722.000000,14136.000000,3.240000,27765.000000,91570.700000,31626.000000,-981.600000,...,2.473400,0.891400,28.189300,14.701600,20.472300,22.934500,0.935400,36.980600,1.470000e+05,2.442600
max,2023.000000,2913.280000,513983.000000,225152.000000,99803.000000,14.980000,130541.000000,256144.000000,122151.000000,49749.000000,...,10.617800,9.332800,196.958900,31.154100,884.860500,36.686300,137.328700,1197.727000,1.608000e+06,8.002800

In [ ]:
df.shape

(161, 23)

Data Preprocessing (Cleaning & Transformation)

In [ ]:
# Check for missing values
df.isnull().sum()

Year                                   0
Company                                0
Category                               0
Market Cap(in B USD)                   1
Revenue                                0
Gross Profit                           0
Net Income                             0
Earning Per Share                      0
EBITDA                                 0
Share Holder Equity                    0
Cash Flow from Operating               0
Cash Flow from Investing               0
Cash Flow from Financial Activities    0
Current Ratio                          0
Debt/Equity Ratio                      0
ROE                                    0
ROA                                    0
ROI                                    0
Net Profit Margin                      0
Free Cash Flow per Share               0
Return on Tangible Equity              0
Number of Employees                    0
Inflation Rate(in US)                  0
dtype: int64

In [ ]:
# Check for duplicated values
df.duplicated().sum()

0

In [ ]:
# Convert Year column to datetime format
df['Year'] = pd.to_datetime(df['Year'], format='%Y')

In [ ]:
df['Profit_Margin_%'] = (df['Net Income'] / df['Revenue']) * 100
df['Profit_Margin_%'] = df['Profit_Margin_%'].fillna(0)  # Replace NaN with 0

In [ ]:
df.sort_values(by=['Company ', 'Year'], inplace=True)  # Ensure correct ordering

df['Revenue_Growth_%'] = df.groupby('Company ')['Revenue'].pct_change() * 100
df['Revenue_Growth_%'] = df['Revenue_Growth_%'].fillna(0)

In [ ]:
df

,Year,Company,Category,Market Cap(in B USD),Revenue,Gross Profit,Net Income,Earning Per Share,EBITDA,Share Holder Equity,...,ROE,ROA,ROI,Net Profit Margin,Free Cash Flow per Share,Return on Tangible Equity,Number of Employees,Inflation Rate(in US),Profit_Margin_%,Revenue_Growth_%
13,2009-01-01,AAPL,IT,189.80,42905.0,17222.0,8235.0,0.3243,12474.0,31640.0,...,26.0272,17.3365,26.0272,19.1936,0.3550,26.4052,36800,-0.3555,19.193567,0.000000
12,2010-01-01,AAPL,IT,296.89,65225.0,25684.0,14013.0,0.5411,19412.0,47791.0,...,29.3214,18.6385,29.3214,21.4841,0.2857,30.0013,49400,1.6400,21.484094,52.021909
11,2011-01-01,AAPL,IT,376.40,108249.0,43818.0,25922.0,0.9886,35604.0,76615.0,...,33.8341,22.2753,33.8341,23.9466,0.6278,35.9115,63300,3.1568,23.946642,65.962438
10,2012-01-01,AAPL,IT,500.61,156508.0,68662.0,41733.0,1.5775,58518.0,118210.0,...,35.3041,23.7033,35.3041,26.6651,0.3394,36.9806,76100,2.0693,26.665091,44.581474
9,2013-01-01,AAPL,IT,504.79,170910.0,64304.0,37037.0,1.4200,55756.0,123549.0,...,29.9776,17.8923,26.3592,21.6705,0.1363,31.4425,84400,1.4648,21.670470,9.202086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,2014-01-01,SHLDQ,Finance,3.51,36188.0,8755.0,-1365.0,-12.8700,-195.0,2183.0,...,-51.1223,-6.1114,-22.2444,-3.7720,-2.7683,106.6922,226000,1.6222,-3.771969,-9.198575
83,2015-01-01,SHLDQ,Finance,2.19,31198.0,7149.0,-1682.0,-15.8200,-889.0,-945.0,...,191.5344,-13.7277,-84.5005,-5.3914,-7.4240,54.6663,196000,0.1186,-5.391371,-13.789101
82,2016-01-01,SHLDQ,Finance,1.11,25146.0,5810.0,-1129.0,-10.5900,-570.0,-1956.0,...,57.6687,-9.9497,-742.1052,-4.4898,14.9014,27.2859,178000,1.2616,-4.489780,-19.398679
81,2017-01-01,SHLDQ,Finance,0.37,22138.0,4686.0,-2221.0,-20.7800,-1610.0,-3824.0,...,58.0805,-23.7236,884.8605,-10.0325,-13.9382,39.5618,140000,2.1301,-10.032523,-11.962141
80,2018-01-01,SHLDQ,Finance,0.04,16702.0,3527.0,-383.0,-3.5700,-52.0,-3723.0,...,10.2874,-5.2740,25.9837,-2.2931,3.0663,7.4225,89900,2.4426,-2.293139,-24.555064

In [ ]:
# Save cleaned dataset for Power BI
df.to_csv("cleaned_financial_data.csv", index=False)

print("Dataset ready for Power BI!")

Dataset ready for Power BI!